/** Programmatic SEO URLs aligned with the mega footer internal link graph. */
export const SEO_NAV_PATHS: readonly { category: string; slug: string }[] = [
  { category: "products", slug: "residential-proxies" },
  { category: "products", slug: "isp-proxies" },
  { category: "products", slug: "datacenter-proxies" },
  { category: "products", slug: "mobile-proxies" },
  { category: "products", slug: "web-unblocker" },
  { category: "tools", slug: "proxy-tester" },
  { category: "tools", slug: "ip-lookup" },
  { category: "tools", slug: "user-agent-generator" },
  { category: "tools", slug: "chrome-extension" },
  { category: "tools", slug: "firefox-addon" },
  { category: "resources", slug: "blog" },
  { category: "resources", slug: "documentation" },
  { category: "resources", slug: "integrations" },
  { category: "resources", slug: "network-status" },
  { category: "locations", slug: "united-states" },
  { category: "locations", slug: "united-kingdom" },
  { category: "locations", slug: "germany" },
  { category: "locations", slug: "japan" },
  { category: "locations", slug: "global-network" },
  { category: "company", slug: "about-us" },
  { category: "company", slug: "affiliate-program" },
  { category: "company", slug: "contact-us" },
  { category: "legal", slug: "terms-of-service" },
  { category: "legal", slug: "privacy-policy" },
  { category: "legal", slug: "kyc-policy" },
] as const;
